### ISSUE TITLE
RedundantModifiers removes static from methods in interfaces

### ISSUE THREAD

**Issue by lfrancke** [solven-eu/cleanthat#438]
Sorry for not giving more details. I'm only on my phone now but don't want to forget this.

Basically cleanthat removes a "static" modifier from methods in interfaces which breaks builds for us.

I can try to provide a simple example later.

**Comment by blacelle** [comment]
Hello,

This has been fixed in https://github.com/solven-eu/cleanthat/blob/master/java/src/main/java/eu/solven/cleanthat/engine/java/refactorer/mutators/UnnecessaryModifier.java#L107

https://github.com/solven-eu/cleanthat/blob/master/CHANGES.MD#unreleased

Let's me release a 2.7 with the fix right now.

Please comfim how you use Cleanthat (through `mvn`, through `spotless`, through Github App ?)

**Comment by blacelle** [comment]
If your project is OSS, I would take a look, to check all available rules over it (no need to activate then on your side, but it is a way to stress Cleanthat over real projects).

**Comment by lfrancke** [comment]
Hi @blacelle, thank you! Sorry, for the earlier terse report.
And thank you for the fix, I did check issues and PRs but didn't see anything.

I used cleanthat with a customer today and ran it across a few thousand files, this was the only error I could detect.
Unfortunately, their code is not OSS :(
I used it via the maven plugin from `spotless`. I'll close this issue.

**Comment by blacelle** [comment]
> I used cleanthat with a customer today and ran it across a few thousand files, this was the only error I could detect.

Thanks a lot for the feedback. I would appreciate any additional feedback, or an informal exchange about the experience around cleanthat.

---

Through spotless, one can force cleanthat version with `<version>2.7</cleanthat>`.
